makecake04/makecake_BE

src/main/java/com/project/makecake/controller/CakeController.java, src/main/java/com/project/makecake/controller/CommentController.java, src/main/java/com/project/makecake/controller/PostController.java, src/main/java/com/project/makecake/model/Cake.java, src/main/java/com/project/makecake/model/Comment.java, src/main/java/com/project/makecake/model/Post.java, src/main/java/com/project/makecake/service/CakeService.java, src/main/java/com/project/makecake/service/CommentService.java, src/main/java/com/project/makecake/service/PostService.java
=> Rename: 변경 코딩 컨벤션 적용

src/main/java/com/project/makecake/service/MypageService.java
=> Perf: 변경 마이페이지 도안탭 최신순 정렬 기능 추가

src/main/java/com/project/makecake/repository/CakeLikeRepository.java, src/main/java/com/project/makecake/repository/CommentRepository.java, src/main/java/com/project/makecake/repository/DesignRepository.java, src/main/java/com/project/makecake/repository/PostLikeRepository.java, src/main/java/com/project/makecake/repository/PostRepository.java, src/main/java/com/project/makecake/repository/ReviewRepository.java, src/main/java/com/project/makecake/repository/StoreLikeRepository.java, src/main/java/com/project/makecake/service/MypageService.java
=> Perf: 변경 마이페이지 조회 api 최신순 정렬 변경

src/main/java/com/project/makecake/model/Cake.java, src/main/java/com/project/makecake/model/Post.java, src/main/java/com/project/makecake/service/CakeService.java, src/main/java/com/project/makecake/service/PostService.java
=> Fix: 케이크, 도안 게시글 좋아요 수정

src/main/java/com/project/makecake/controller/StoreController.java, src/main/java/com/project/makecake/service/StoreService.java
좋아요수를 바로 반영하기 위해 store 좋아요 Response에 likeCnt 추가
=> Fix: 변경 매장 좋아요 Response 수정

src/main/java/com/project/makecake/service/CakeService.java, src/main/java/com/project/makecake/service/PostService.java
좋아요 요청이 잘못 오는 경우를 대비해 좋아요 로직에 exception 추가
=> Perf: 변경 케이크, 게시글 좋아요 exception 추가

src/main/java/com/project/makecake/controller/UserController.java
=> Rename: 변경 프로필수정 api 변경

scripts/start.sh
=> Rename: 변경 start.sh 변경

scripts/health.sh, scripts/profile.sh
=> Rename: 변경 health.sh profile.sh 변경

scripts/health.sh
=> Rename: 변경 health.sh 변경

src/main/java/com/project/makecake/service/UserService.java
=> Rename: 변경 save -> saved

src/main/java/com/project/makecake/service/UserService.java
=> Comment:  추가 UserService 주석 1줄 추가

.github/workflows/gradle.yml, .gitignore
=> Feat: 변경 github action 변경

src/main/java/com/project/makecake/repository/PersonalNotiRepository.java, src/main/java/com/project/makecake/service/NotiService.java
새 알림 확인할 때 findBy쿼리말고 exist쿼리로 변경
=> Fix: 변경 새로운 알림 여부 조회 수정

src/main/java/com/project/makecake/dto/MyReactCakeResponseDto.java, src/main/java/com/project/makecake/service/MypageService.java
=> Feat: 추가 내가 반응한 케이크 storeId 추가

src/main/java/com/project/makecake/repository/CakeLikeRepository.java, src/main/java/com/project/makecake/repository/PostLikeRepository.java, src/main/java/com/project/makecake/service/CakeService.java, src/main/java/com/project/makecake/service/PostService.java
=> Fix: 변경 좋아요 로직 수정

src/main/java/com/project/makecake/exceptionhandler/RestApiExceptionHandler.java
uses unchecked or unsafe operations 해결을 위해 코드 약간 수정
=> Fix: 변경 익셉션 핸들러 약간 수정

src/main/java/com/project/makecake/service/MypageService.java
=> Perf: 변경 MypageService 내가 남긴 댓글 수 변경

src/main/java/com/project/makecake/repository/CakeRepository.java, src/main/java/com/project/makecake/service/CakeService.java
=> Perf: 변경 cake 순서 변경

src/main/java/com/project/makecake/security/WebSecurityConfig.java
=> Perf: 추가 security 추가

src/main/java/com/project/makecake/model/Cake.java, src/main/java/com/project/makecake/model/CakeLike.java, src/main/java/com/project/makecake/model/CakeMenu.java, src/main/java/com/project/makecake/model/Comment.java, src/main/java/com/project/makecake/model/Design.java, src/main/java/com/project/makecake/model/Menu.java, src/main/java/com/project/makecake/model/OpenTime.java, src/main/java/com/project/makecake/model/Post.java, src/main/java/com/project/makecake/model/PostLike.java, src/main/java/com/project/makecake/model/Review.java, src/main/java/com/project/makecake/model/ReviewImg.java, src/main/java/com/project/makecake/model/Store.java, src/main/java/com/project/makecake/model/StoreLike.java, src/main/java/com/project/makecake/model/StoreOption.java, src/main/java/com/project/makecake/model/StoreUrl.java, src/main/java/com/project/makecake/model/User.java
=> Perf: 변경 아이디 생성 전략 변경

src/main/java/com/project/makecake/model/Cake.java, src/main/java/com/project/makecake/model/Design.java, src/main/java/com/project/makecake/model/Post.java, src/main/java/com/project/makecake/model/Review.java, src/main/java/com/project/makecake/model/Store.java, src/main/java/com/project/makecake/model/User.java
=> Fix: 아이디 생성 전략 몇개 롤백

src/main/java/com/project/makecake/service/CommentService.java, src/main/java/com/project/makecake/service/PostService.java
=> Perf: 변경 댓글, 좋아요 알림 리다이렉트 변경

src/main/java/com/project/makecake/service/GoogleLoginService.java, src/main/java/com/project/makecake/service/KakaoLoginService.java, src/main/java/com/project/makecake/service/NaverLoginService.java, src/main/java/com/project/makecake/service/UserService.java
=> Perf: 변경 유저 기본이미지 변경

src/main/java/com/project/makecake/service/UserOrdersService.java
=> Fix: 변경 주문서 갯수 변경

logback.xml, src/main/java/com/project/makecake/config/Interceptor.java, src/main/java/com/project/makecake/config/WebConfig.java, src/main/java/com/project/makecake/security/JwtAuthenticationFilter.java, src/main/java/com/project/makecake/security/JwtAuthorizationFilter.java, src/main/java/com/project/makecake/service/GoogleLoginService.java, src/main/java/com/project/makecake/service/KakaoLoginService.java, src/main/java/com/project/makecake/service/NaverLoginService.java, src/main/java/com/project/makecake/service/UserService.java
=> Feat: 추가 log 추가

src/main/java/com/project/makecake/controller/UserController.java, src/main/java/com/project/makecake/service/CakeService.java, src/main/java/com/project/makecake/service/PostService.java, src/main/java/com/project/makecake/service/ReviewService.java, src/main/java/com/project/makecake/service/S3Service.java, src/main/java/com/project/makecake/service/UserService.java
=> Perf: 변경 이미지 업로드 메소드 추가

src/main/java/com/project/makecake/service/MypageService.java
=> Perf: 변경 마이페이지 변경

src/main/java/com/project/makecake/repository/CakeRepository.java
=> Perf: 변경 케이크 모아보기 랜덤 추가

src/main/java/com/project/makecake/service/CommentService.java, src/main/java/com/project/makecake/service/PostService.java
=> Perf: 변경 길이 검사 추가

src/main/java/com/project/makecake/service/CakeService.java
=> Perf: 변경 케이크 리스트 썸네일 반영

src/main/java/com/project/makecake/controller/backoffice/BOCakeController.java, src/main/java/com/project/makecake/controller/backoffice/BONotiController.java, src/main/java/com/project/makecake/service/backoffice/BOCakeService.java, src/main/java/com/project/makecake/service/backoffice/BONotiService.java
=> Refactor: 변경 백오피스 클래스 이름 변경

src/main/java/com/project/makecake/security/WebSecurityConfig.java
=> Fix: 변경 소셜로그인
